In [1]:
import requests
import json
import pandas as pd
import regex as re
import os
import numpy as np

In [2]:
import os
from dotenv import load_dotenv

In [3]:
url = "https://api.bls.gov/publicAPI/v2/timeseries/data/"
headers = {'Content-type': 'application/json'}
api_key = os.getenv('PROJECT_API_KEY')

In [4]:
load_dotenv()
api_key = os.getenv('PROJECT_API_KEY')

if not api_key:
    print("API key not found!")
else:
    print(f"API key loaded")

API key loaded

In [5]:
item_code = {
'APU0000701111',
 'APU0000701312',
 'APU0000701322',
 'APU0000702111',
 'APU0000702212',
 'APU0000702421',
 'APU0000703111',
 'APU0000703112',
 'APU0000703113',
 'APU0000703213',
 'APU0000703311',
 'APU0000703432',
 'APU0000703511',
 'APU0000703512',
 'APU0000703613',
 'APU0000704111',
 'APU0000704211',
 'APU0000704212',
 'APU0000704312',
 'APU0000706111',
 'APU0000706212',
 'APU0000708111',
 'APU0000709112',
 'APU0000710211',
 'APU0000710212',
 'APU0000710411',
 'APU0000711211',
 'APU0000711311',
 'APU0000711411',
 'APU0000711412',
 'APU0000711415',
 'APU0000712112',
 'APU0000712211',
 'APU0000712311',
 'APU0000713111',
 'APU0000714221',
 'APU0000714233',
 'APU0000715211',
 'APU0000717311',
 'APU0000718311',
#  'APU0000720111',
#  'APU0000720222',
#  'APU0000720311',
 'APU0000FC1101',
#  'APU0000FC2101',
#  'APU0000FC3101',
#  'APU0000FC4101',
 'APU0000FD2101',
 'APU0000FD3101',
#  'APU0000FD4101',
 'APU0000FF1101',
 'APU0000FJ1101',
 'APU0000FJ4101',
 'APU0000FL2101',
 'APU0000FN1101',
 'APU0000FN1102',
 'APU0000FS1101'
}

In [6]:
data = {
    "seriesid": list(item_code),
    "startyear": "2025",
    "endyear": "2026",
    "registrationkey": api_key
}

response = requests.post(url, data=json.dumps(data), headers=headers)
response_data = response.json()

if response_data.get('status') == 'REQUEST_SUCCEEDED':
    if 'series' in response_data['Results'] and response_data['Results']['series']:
        for series_data in response_data['Results']['series']:
            print(f"Data for series ID {series_data['seriesID']}: {series_data['data'][:5]}")  # Print first 5 data points
    else:
        print("No data available for the provided series IDs.")
else:
    print(f"Failed to fetch data. Status: {response_data.get('status')}")

Data for series ID APU0000717311: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '9.459', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '9.366', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '9.053', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '9.258', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000704212: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '4.496', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '4.433', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '4.671', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '4.391', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000FN1102: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '0.593', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '0.611', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '0.548', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '0.549', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000710212: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '5.987', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '5.982', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '5.789', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '5.636', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000FL2101: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '3.560', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '3.379', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '3.466', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '3.399', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000711311: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '1.508', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '1.536', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '1.570', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}, {'year': '2025', 'period': 'M09', 'periodName': 'September', 'value': '1.803', 'footnotes': [{}]}]
Data for series ID APU0000712311: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '1.902', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '1.791', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '1.840', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '1.828', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000FF1101: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '4.142', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '4.165', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '4.153', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '4.150', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000701111: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '0.549', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '0.565', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '0.554', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '0.552', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000709112: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '4.026', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '4.100', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '4.047', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '3.997', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000703613: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '14.191', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '13.837', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '14.027', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '13.342', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000FS1101: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '4.314', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '4.383', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '4.408', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '4.310', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000703311: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '8.587', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '8.546', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '8.853', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '8.943', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000708111: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '2.500', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '2.577', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '2.712', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '2.860', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000706212: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '1.707', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '1.735', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '1.725', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '1.795', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000FD2101: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '4.481', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '4.434', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '4.309', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '4.394', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000703112: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '6.739', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '6.752', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '6.687', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '6.540', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000702111: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '1.850', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '1.843', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '1.833', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '1.790', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000FC1101: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '6.895', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '6.868', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '6.821', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '6.781', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000711415: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '2.929', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '3.075', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '3.606', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}, {'year': '2025', 'period': 'M09', 'periodName': 'September', 'value': '2.573', 'footnotes': [{}]}]
Data for series ID APU0000704211: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '4.564', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '4.453', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '4.716', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '4.526', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000710211: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '4.680', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '4.845', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '4.734', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '4.725', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000714233: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '1.704', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '1.702', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '1.689', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '1.686', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000701322: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '1.323', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '1.325', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '1.311', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '1.300', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000702421: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '5.255', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '5.352', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '5.128', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '5.331', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000703511: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '10.095', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '9.836', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '9.875', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '9.665', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000703432: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '8.358', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '8.463', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '8.630', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '9.172', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000702212: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '2.687', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '2.729', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '2.677', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '2.638', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000703213: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '8.957', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '8.709', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '8.951', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '9.343', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000714221: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '1.312', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '1.298', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '1.164', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '1.174', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000FJ4101: [{'year': '2026', 'period': 'M02', 'periodName': 'February', 'latest': 'true', 'value': '1.498', 'footnotes': [{}]}, {'year': '2026', 'period': 'M01', 'periodName': 'January', 'value': '1.564', 'footnotes': [{}]}, {'year': '2025', 'period': 'M12', 'periodName': 'December', 'value': '1.518', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '1.556', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}]
Data for series ID APU0000712211: [{'year': '2026', 'period': 'M01', 'periodName': 'January', 'latest': 'true', 'value': '1.699', 'footnotes': [{}]}, {'year': '2025', 'period': 'M11', 'periodName': 'November', 'value': '1.987', 'footnotes': [{}]}, {'year': '2025', 'period': 'M10', 'periodName': 'October', 'value': '-', 'footnotes': [{'code': 'X', 'text': 'Data unavailable due to the 2025 lapse in appropriations'}]}, {'year': '2025', 'period': 'M09', 'periodName': 'September', 'value': '1.731', 'footnotes': [{}]}, {'year': '2025', 'period': 'M08', 'periodName': 'August', 'value': '1.673', 'footnotes': [{}]}]

In [7]:
response_data

{'status': 'REQUEST_SUCCEEDED',
 'responseTime': 293,
 'message': [],
 'Results': {'series': [{'seriesID': 'APU0000717311',
    'data': [{'year': '2026',
      'period': 'M02',
      'periodName': 'February',
      'latest': 'true',
      'value': '9.459',
      'footnotes': [{}]},
     {'year': '2026',
      'period': 'M01',
      'periodName': 'January',
      'value': '9.366',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M12',
      'periodName': 'December',
      'value': '9.053',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M11',
      'periodName': 'November',
      'value': '9.258',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M10',
      'periodName': 'October',
      'value': '-',
      'footnotes': [{'code': 'X',
        'text': 'Data unavailable due to the 2025 lapse in appropriations'}]},
     {'year': '2025',
      'period': 'M09',
      'periodName': 'September',
      'value': '9.139',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M08',
      'periodName': 'August',
      'value': '8.872',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'value': '8.414',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '8.132',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '7.931',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '7.536',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '7.385',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '7.246',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '7.019',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000704212',
    'data': [{'year': '2026',
      'period': 'M02',
      'periodName': 'February',
      'latest': 'true',
      'value': '4.496',
      'footnotes': [{}]},
     {'year': '2026',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.433',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M12',
      'periodName': 'December',
      'value': '4.671',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M11',
      'periodName': 'November',
      'value': '4.391',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M10',
      'periodName': 'October',
      'value': '-',
      'footnotes': [{'code': 'X',
        'text': 'Data unavailable due to the 2025 lapse in appropriations'}]},
     {'year': '2025',
      'period': 'M09',
      'periodName': 'September',
      'value': '4.748',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M08',
      'periodName': 'August',
      'value': '4.688',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'value': '4.691',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '4.618',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '4.601',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '4.609',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '4.771',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '4.558',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.530',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000FN1102',
    'data': [{'year': '2026',
      'period': 'M02',
      'periodName': 'February',
      'latest': 'true',
      'value': '0.593',
      'footnotes': [{}]},
     {'year': '2026',
      'period': 'M01',
      'periodName': 'January',
      'value': '0.611',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M12',
      'periodName': 'December',
      'value': '0.548',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M11',
      'periodName': 'November',
      'value': '0.549',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M10',
      'periodName': 'October',
      'value': '-',
      'footnotes': [{'code': 'X',
        'text': 'Data unavailable due to the 2025 lapse in appropriations'}]},
     {'year': '2025',
      'period': 'M09',
      'periodName': 'September',
      'value': '0.569',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M08',
      'periodName': 'August',
      'value': '0.567',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'value': '0.565',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '0.579',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '0.558',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '0.581',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '0.583',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '0.572',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '0.582',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000710212',
    'data': [{'year': '2026',
      'period': 'M02',
      'periodName': 'February',
      'latest': 'true',
      'value': '5.987',
      'footnotes': [{}]},
     {'year': '2026',
      'period': 'M01',
      'periodName': 'January',
      'value': '5.982',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M12',
      'periodName': 'December',
      'value': '5.789',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M11',
      'periodName': 'November',
      'value': '5.636',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M10',
      'periodName': 'October',
      'value': '-',
      'footnotes': [{'code': 'X',
        'text': 'Data unavailable due to the 2025 lapse in appropriations'}]},
     {'year': '2025',
      'period': 'M09',
      'periodName': 'September',
      'value': '6.049',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M08',
      'periodName': 'August',
      'value': '6.123',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'value': '6.041',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '5.999',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '5.908',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '5.743',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '5.737',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '5.536',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '5.698',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000FL2101',
    'data': [{'year': '2026',
      'period': 'M02',
      'periodName': 'February',
      'latest': 'true',
      'value': '3.560',
      'footnotes': [{}]},
     {'year': '2026',
      'period': 'M01',
      'periodName': 'January',
      'value': '3.379',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M12',
      'periodName': 'December',
      'value': '3.466',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M11',
      'periodName': 'November',
      'value': '3.399',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M10',
      'periodName': 'October',
      'value': '-',
      'footnotes': [{'code': 'X',
        'text': 'Data unavailable due to the 2025 lapse in appropriations'}]},
     {'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'value': '3.006',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '2.951',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '2.994',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '2.915',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '2.923',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '2.865',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '2.831',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000711311',
    'data': [{'year': '2026',
      'period': 'M02',
      'periodName': 'February',
      'latest': 'true',
      'value': '1.508',
      'footnotes': [{}]},
     {'year': '2026',
      'period': 'M01',
      'periodName': 'January',
      'value': '1.536',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M12',
      'periodName': 'December',
      'value': '1.570',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M10',
      'periodName': 'October',
      'value': '-',
      'footnotes': [{'code': 'X',
        'text': 'Data unavailable due to the 2025 lapse in appropriations'}]},
     {'year': '2025',
      'period': 'M09',
      'periodName': 'September',
      'value': '1.803',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M08',
      'periodName': 'August',
      'value': '1.795',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '1.633',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '1.564',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '1.485',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '1.484',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '1.536',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '1.531',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000712311',
    'data': [{'year': '2026',
      'period': 'M02',
      'periodName': 'February',
      'latest': 'true',
      'value': '1.902',
      'footnotes': [{}]},
     {'year': '2026',
      'period': 'M01',
      'periodName': 'January',
      'value': '1.791',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M12',
      'periodName': 'December',
      'value': '1.840',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M11',
      'periodName': 'November',
      'value': '1.828',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M10',
      'periodName': 'October',
      'value': '-',
      'footnotes': [{'code': 'X',
        'text': 'Data unavailable due to the 2025 lapse in appropriations'}]},
     {'year': '2025',
      'period': 'M09',
      'periodName': 'September',
      'value': '1.910',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M08',
      'periodName': 'August',
      'value': '1.925',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'value': '1.793',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '1.737',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '1.705',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '1.793',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '1.819',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '1.848',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '2.050',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000FF1101',
    'data': [{'year': '2026',
      'period': 'M02',
      'periodName': 'February',
      'latest': 'true',
      'value': '4.142',
      'footnotes': [{}]},
     {'year': '2026',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.165',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M12',
      'periodName': 'December',
      'value': '4.153',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M11',
      'periodName': 'November',
      'value': '4.150',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M10',
      'periodName': 'October',
      'value': '-',
      'footnotes': [{'code': 'X',
        'text': 'Data unavailable due to the 2025 lapse in appropriations'}]},
     {'year': '2025',
      'period': 'M09',
      'periodName': 'September',
      'value': '4.172',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M08',
      'periodName': 'August',
      'value': '4.212',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'value': '4.204',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '4.239',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '4.216',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '4.180',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '4.160',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '4.079',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '3.969',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000701111',
    'data': [{'year': '2026',
      'period': 'M02',
      'periodName': 'February',
      'latest': 'true',
      'value': '0.549',
      'footnotes': [{}]},
     {'year': '2026',
      'period': 'M01',
      'periodName': 'January',
      'value': '0.565',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M12',
      'periodName': 'December',
      'value': '0.554',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M11',
      'periodName': 'November',
      'value': '0.552',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M10',
      'periodName': 'October',
      'value': '-',
      'footnotes': [{'code': 'X',
        'text': 'Data unavailable due to the 2025 lapse in appropriations'}]},
     {'year': '2025',
      'period': 'M09',
      'periodName': 'September',
      'value': '0.563',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M08',
      'periodName': 'August',
      'value': '0.557',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'value': '0.557',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '0.574',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '0.562',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '0.557',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '0.565',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '0.561',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '0.561',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000709112',
    'data': [{'year': '2026',
      'period': 'M02',
      'periodName': 'February',
      'latest': 'true',
      'value': '4.026',
      'footnotes': [{}]},
     {'year': '2026',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.100',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M12',
      'periodName': 'December',
      'value': '4.047',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M11',
      'periodName': 'November',
      'value': '3.997',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M10',
      'periodName': 'October',
      'value': '-',
      'footnotes': [{'code': 'X',
        'text': 'Data unavailable due to the 2025 lapse in appropriations'}]},
     {'year': '2025',
      'period': 'M09',
      'periodName': 'September',
      'value': '4.129',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M08',
      'periodName': 'August',
      'value': '4.171',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'value': '4.162',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '4.029',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '4.022',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '4.074',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '4.050',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '4.026',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.025',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000703613',
    'data': [{'year': '2026',
      'period': 'M02',
      'periodName': 'February',
      'latest': 'true',
      'value': '14.191',
      'footnotes': [{}]},
     {'year': '2026',
      'period': 'M01',
      'periodName': 'January',
      'value': '13.837',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M12',
      'periodName': 'December',
      'value': '14.027',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M11',
      'periodName': 'November',
      'value': '13.342',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M10',
      'periodName': 'October',
      'value': '-',
      'footnotes': [{'code': 'X',
        'text': 'Data unavailable due to the 2025 lapse in appropriations'}]},
     {'year': '2025',
      'period': 'M09',
      'periodName': 'September',
      'value': '14.135',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M08',
      'periodName': 'August',
      'value': '14.319',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'value': '13.554',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '12.923',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',

In [8]:
if 'Results' in response_data and 'series' in response_data['Results']:
    series_list = response_data['Results']['series']
    response_df = pd.DataFrame([
        {
            'seriesID': series['seriesID'],
            **data_point
        }
        for series in series_list
        for data_point in series['data']
    ])
else:
    print("No data available to convert to DataFrame.")

In [9]:
response_df.to_csv('data/bls_data.csv', index=False)

In [10]:
response_df['seriesID'].value_counts()

seriesID
APU0000717311    14
APU0000704312    14
APU0000703432    14
APU0000702212    14
APU0000703213    14
APU0000714221    14
APU0000FJ4101    14
APU0000703111    14
APU0000713111    14
APU0000711211    14
APU0000701312    14
APU0000715211    14
APU0000702421    14
APU0000FD3101    14
APU0000FN1101    14
APU0000710411    14
APU0000FJ1101    14
APU0000704111    14
APU0000703113    14
APU0000706111    14
APU0000711412    14
APU0000711411    14
APU0000704212    14
APU0000703511    14
APU0000701322    14
APU0000708111    14
APU0000FN1102    14
APU0000710212    14
APU0000712311    14
APU0000FF1101    14
APU0000701111    14
APU0000709112    14
APU0000703613    14
APU0000FS1101    14
APU0000714233    14
APU0000703311    14
APU0000706212    14
APU0000FD2101    14
APU0000703112    14
APU0000702111    14
APU0000FC1101    14
APU0000704211    14
APU0000710211    14
APU0000718311    14
APU0000712112    13
APU0000711415    13
APU0000703512    12
APU0000712211    12
APU0000711311    12
APU0000FL2101    12
Name: count, dtype: int64

In [11]:
response_df['date'] = pd.to_datetime(response_df['periodName'] + ' ' + response_df['year'].astype(str), format='%B %Y')

In [12]:
response_df

,seriesID,year,period,periodName,latest,value,footnotes,date
0,APU0000717311,2026,M02,February,true,9.459,[{}],2026-02-01
1,APU0000717311,2026,M01,January,NaN,9.366,[{}],2026-01-01
2,APU0000717311,2025,M12,December,NaN,9.053,[{}],2025-12-01
3,APU0000717311,2025,M11,November,NaN,9.258,[{}],2025-11-01
4,APU0000717311,2025,M10,October,NaN,-,"[{'code': 'X', 'text': 'Data unavailable due t...",2025-10-01
...,...,...,...,...,...,...,...,...
685,APU0000718311,2025,M05,May,NaN,6.731,[{}],2025-05-01
686,APU0000718311,2025,M04,April,NaN,6.611,[{}],2025-04-01
687,APU0000718311,2025,M03,March,NaN,6.536,[{}],2025-03-01
688,APU0000718311,2025,M02,February,NaN,6.462,[{}],2025-02-01
689,APU0000718311,2025,M01,January,NaN,6.474,[{}],2025-01-01

In [13]:
longform_df = response_df.pivot(index='date', columns='seriesID', values='value')
print(longform_df.head())

seriesID   APU0000701111 APU0000701312 APU0000701322 APU0000702111  \
date
2025-01-01         0.561         1.008         1.366         1.925
2025-02-01         0.561         1.030         1.381         1.925
2025-03-01         0.565         1.038         1.379         1.880
2025-04-01         0.557         1.031         1.361         1.913
2025-05-01         0.562         1.067         1.322         1.876

seriesID   APU0000702212 APU0000702421 APU0000703111 APU0000703112  \
date
2025-01-01         2.760         4.895         5.495         5.545
2025-02-01         2.759         4.658         5.744         5.625
2025-03-01         2.719         4.863         5.854         5.790
2025-04-01         2.751         4.956         5.996         5.801
2025-05-01         2.602         5.049         6.018         5.981

seriesID   APU0000703113 APU0000703213  ... APU0000FC1101 APU0000FD2101  \
date                                    ...
2025-01-01         7.110         7.694  ...         5.820         4.411
2025-02-01         7.244         8.104  ...         5.961         4.428
2025-03-01         7.476         8.097  ...         6.137         4.496
2025-04-01         7.551         7.980  ...         6.142         4.451
2025-05-01         7.688         7.875  ...         6.245         4.451

seriesID   APU0000FD3101 APU0000FF1101 APU0000FJ1101 APU0000FJ4101  \
date
2025-01-01         4.249         3.969         3.784         1.489
2025-02-01         4.226         4.079         3.798         1.515
2025-03-01         4.341         4.160         3.851         1.520
2025-04-01         4.244         4.180         3.850         1.538
2025-05-01         4.220         4.216         3.777         1.577

seriesID   APU0000FL2101 APU0000FN1101 APU0000FN1102 APU0000FS1101
date
2025-01-01         2.831         2.093         0.582         4.912
2025-02-01         2.865         2.101         0.572         4.869
2025-03-01         2.923         2.103         0.583         4.816
2025-04-01         2.915         2.104         0.581         4.780
2025-05-01         2.994         2.129         0.558         4.952

[5 rows x 50 columns]

In [14]:
longform_df

seriesID,APU0000701111,APU0000701312,APU0000701322,APU0000702111,APU0000702212,APU0000702421,APU0000703111,APU0000703112,APU0000703113,APU0000703213,...,APU0000FC1101,APU0000FD2101,APU0000FD3101,APU0000FF1101,APU0000FJ1101,APU0000FJ4101,APU0000FL2101,APU0000FN1101,APU0000FN1102,APU0000FS1101
date,,,,,,,,,,,,,,,,,,,,,
2025-01-01,0.561,1.008,1.366,1.925,2.760,4.895,5.495,5.545,7.110,7.694,...,5.820,4.411,4.249,3.969,3.784,1.489,2.831,2.093,0.582,4.912
2025-02-01,0.561,1.030,1.381,1.925,2.759,4.658,5.744,5.625,7.244,8.104,...,5.961,4.428,4.226,4.079,3.798,1.515,2.865,2.101,0.572,4.869
2025-03-01,0.565,1.038,1.379,1.880,2.719,4.863,5.854,5.790,7.476,8.097,...,6.137,4.496,4.341,4.160,3.851,1.520,2.923,2.103,0.583,4.816
2025-04-01,0.557,1.031,1.361,1.913,2.751,4.956,5.996,5.801,7.551,7.980,...,6.142,4.451,4.244,4.180,3.850,1.538,2.915,2.104,0.581,4.780
2025-05-01,0.562,1.067,1.322,1.876,2.602,5.049,6.018,5.981,7.688,7.875,...,6.245,4.451,4.220,4.216,3.777,1.577,2.994,2.129,0.558,4.952
2025-06-01,0.574,1.061,1.318,1.864,2.656,5.108,6.103,6.120,7.672,8.197,...,6.342,4.401,4.264,4.239,3.592,1.494,2.951,2.183,0.579,4.872
2025-07-01,0.557,1.068,1.306,1.851,2.714,5.264,6.338,6.254,8.035,8.439,...,6.504,4.660,4.333,4.204,3.662,1.556,3.006,2.199,0.565,4.797
2025-08-01,0.557,1.059,1.294,1.841,2.684,5.122,6.626,6.318,7.950,8.845,...,6.631,4.501,4.299,4.212,3.663,1.495,NaN,2.208,0.567,4.828
2025-09-01,0.563,1.060,1.205,1.867,2.775,5.150,6.326,6.323,8.182,9.232,...,6.643,4.533,4.349,4.172,3.648,1.533,NaN,2.234,0.569,4.787
2025-10-01,-,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
2025-11-01,0.552,1.065,1.300,1.790,2.638,5.331,6.504,6.540,8.232,9.343,...,6.781,4.394,4.097,4.150,3.410,1.556,3.399,2.093,0.549,4.310
2025-12-01,0.554,1.076,1.311,1.833,2.677,5.128,6.521,6.687,8.254,8.951,...,6.821,4.309,4.298,4.153,3.372,1.518,3.466,1.975,0.548,4.408
2026-01-01,0.565,1.059,1.325,1.843,2.729,5.352,6.693,6.752,8.191,8.709,...,6.868,4.434,4.150,4.165,3.426,1.564,3.379,2.115,0.611,4.383
2026-02-01,0.549,1.074,1.323,1.850,2.687,5.255,6.703,6.739,8.338,8.957,...,6.895,4.481,4.191,4.142,3.409,1.498,3.560,2.215,0.593,4.314

In [15]:
response_df['seriesID']

0      APU0000717311
1      APU0000717311
2      APU0000717311
3      APU0000717311
4      APU0000717311
           ...
685    APU0000718311
686    APU0000718311
687    APU0000718311
688    APU0000718311
689    APU0000718311
Name: seriesID, Length: 690, dtype: object

In [16]:
series_name = pd.read_csv('data/series_name.csv', index_col=0)

In [17]:
response_df = response_df.merge(series_name, left_on='seriesID', right_index=True, how='left')
response_df.head()

,seriesID,year,period,periodName,latest,value,footnotes,date,item_name
0,APU0000717311,2026,M02,February,true,9.459,[{}],2026-02-01,"Coffee, 100%, ground roast, all sizes, per lb."
1,APU0000717311,2026,M01,January,NaN,9.366,[{}],2026-01-01,"Coffee, 100%, ground roast, all sizes, per lb."
2,APU0000717311,2025,M12,December,NaN,9.053,[{}],2025-12-01,"Coffee, 100%, ground roast, all sizes, per lb."
3,APU0000717311,2025,M11,November,NaN,9.258,[{}],2025-11-01,"Coffee, 100%, ground roast, all sizes, per lb."
4,APU0000717311,2025,M10,October,NaN,-,"[{'code': 'X', 'text': 'Data unavailable due t...",2025-10-01,"Coffee, 100%, ground roast, all sizes, per lb."

In [18]:
longform_df = response_df.pivot(index='date', columns='item_name', values='value')
longform_df.head()

item_name,"All Ham (Excluding Canned Ham and Luncheon Slices), per lb.","All Pork Chops, per lb.","All soft drinks, 12 pk, 12 oz., cans, per 12 oz.","All soft drinks, per 2 liters","All uncooked ground beef, per lb.","American processed cheese, per lb.","Bacon, sliced, per lb.","Bananas, per lb.","Beans, dried, any type, all sizes, per lb.","Beef for stew, boneless, per lb.",...,"Rice, white, long grain, uncooked, per lb.","Round roast, USDA Choice, boneless, per lb.","Spaghetti and macaroni, per lb.","Steak, round, USDA Choice, boneless, per lb.","Steak, round, graded and ungraded, excluding USDA Prime and Choice, per lb.","Steak, sirloin, USDA Choice, boneless, per lb.","Strawberries, dry pint, per 12 oz.","Sugar, white, all sizes, per lb.","Tomatoes, field grown, per lb.","Yogurt, per 8 oz."
date,,,,,,,,,,,,,,,,,,,,,
2025-01-01,4.411,4.249,0.582,2.093,5.820,5.058,7.044,0.621,1.654,7.318,...,1.008,7.270,1.366,8.280,8.055,11.965,3.295,1.011,2.050,1.489
2025-02-01,4.428,4.226,0.572,2.101,5.961,5.026,6.798,0.619,1.631,7.677,...,1.030,7.490,1.381,8.485,8.128,11.899,2.905,1.012,1.848,1.515
2025-03-01,4.496,4.341,0.583,2.103,6.137,4.946,6.978,0.625,1.640,7.601,...,1.038,7.557,1.379,8.554,8.155,11.924,2.361,1.014,1.819,1.520
2025-04-01,4.451,4.244,0.581,2.104,6.142,4.987,7.009,0.635,1.674,7.733,...,1.031,7.616,1.361,8.627,8.126,12.326,2.475,1.021,1.793,1.538
2025-05-01,4.451,4.220,0.558,2.129,6.245,5.063,6.985,0.655,1.669,7.729,...,1.067,7.570,1.322,8.401,8.199,12.207,2.397,1.054,1.705,1.577

### Export data for multiple charts

In [19]:
longform_df.to_csv('data/bls_chart.csv')

## Prepare data for table format

### Get the latest rows for percent change

In [20]:
latest_rows = longform_df.tail(2)
latest_rows

item_name,"All Ham (Excluding Canned Ham and Luncheon Slices), per lb.","All Pork Chops, per lb.","All soft drinks, 12 pk, 12 oz., cans, per 12 oz.","All soft drinks, per 2 liters","All uncooked ground beef, per lb.","American processed cheese, per lb.","Bacon, sliced, per lb.","Bananas, per lb.","Beans, dried, any type, all sizes, per lb.","Beef for stew, boneless, per lb.",...,"Rice, white, long grain, uncooked, per lb.","Round roast, USDA Choice, boneless, per lb.","Spaghetti and macaroni, per lb.","Steak, round, USDA Choice, boneless, per lb.","Steak, round, graded and ungraded, excluding USDA Prime and Choice, per lb.","Steak, sirloin, USDA Choice, boneless, per lb.","Strawberries, dry pint, per 12 oz.","Sugar, white, all sizes, per lb.","Tomatoes, field grown, per lb.","Yogurt, per 8 oz."
date,,,,,,,,,,,,,,,,,,,,,
2026-01-01,4.434,4.150,0.611,2.115,6.868,4.845,6.978,0.653,1.702,8.463,...,1.059,8.546,1.325,9.836,9.057,13.837,3.075,1.022,1.791,1.564
2026-02-01,4.481,4.191,0.593,2.215,6.895,4.680,6.904,0.653,1.704,8.358,...,1.074,8.587,1.323,10.095,NaN,14.191,2.929,1.016,1.902,1.498

In [21]:
transposed_latest_rows = latest_rows.transpose()
transposed_latest_rows.head()

date                                               2026-01-01 2026-02-01
item_name
All Ham (Excluding Canned Ham and Luncheon Slic...      4.434      4.481
All Pork Chops, per lb.                                 4.150      4.191
All soft drinks, 12 pk, 12 oz., cans, per 12 oz.        0.611      0.593
All soft drinks, per 2 liters                           2.115      2.215
All uncooked ground beef, per lb.                       6.868      6.895

### Get percentage change

In [22]:
transposed_latest_rows = transposed_latest_rows.dropna()
transposed_latest_rows.head()

date                                               2026-01-01 2026-02-01
item_name
All Ham (Excluding Canned Ham and Luncheon Slic...      4.434      4.481
All Pork Chops, per lb.                                 4.150      4.191
All soft drinks, 12 pk, 12 oz., cans, per 12 oz.        0.611      0.593
All soft drinks, per 2 liters                           2.115      2.215
All uncooked ground beef, per lb.                       6.868      6.895

In [23]:
transposed_latest_rows = transposed_latest_rows.replace('-', pd.NA)

In [24]:
transposed_latest_rows['change'] = transposed_latest_rows.apply(
    lambda row: ((float(row.iloc[1]) - float(row.iloc[0])) / float(row.iloc[0]) * 100) if pd.notna(row.iloc[0]) and pd.notna(row.iloc[1]) else None,
    axis=1
)
transposed_latest_rows

date,2026-01-01 00:00:00,2026-02-01 00:00:00,change
item_name,,,
"All Ham (Excluding Canned Ham and Luncheon Slices), per lb.",4.434,4.481,1.059991
"All Pork Chops, per lb.",4.150,4.191,0.987952
"All soft drinks, 12 pk, 12 oz., cans, per 12 oz.",0.611,0.593,-2.945990
"All soft drinks, per 2 liters",2.115,2.215,4.728132
"All uncooked ground beef, per lb.",6.868,6.895,0.393128
"American processed cheese, per lb.",4.845,4.680,-3.405573
"Bacon, sliced, per lb.",6.978,6.904,-1.060476
"Bananas, per lb.",0.653,0.653,0.000000
"Beans, dried, any type, all sizes, per lb.",1.702,1.704,0.117509
"Beef for stew, boneless, per lb.",8.463,8.358,-1.240695
"Bread, white, pan, per lb.",1.843,1.850,0.379816
"Bread, whole wheat, pan, per lb.",2.729,2.687,-1.539025
"Butter, stick, per lb.",4.383,4.314,-1.574264
"Cheddar cheese, natural, per lb.",5.982,5.987,0.083584
"Chicken breast, boneless, per lb.",4.165,4.142,-0.552221
"Chicken legs, bone-in, per lb.",1.735,1.707,-1.613833
"Chicken, fresh, whole, per lb.",2.041,2.049,0.391965
"Chops, boneless, per lb.",4.433,4.496,1.421159
"Chops, center cut, bone-in, per lb.",4.453,4.564,2.492702
"Chuck roast, USDA Choice, boneless, per lb.",8.709,8.957,2.847629
"Coffee, 100%, ground roast, all sizes, per lb.",9.366,9.459,0.992953
"Cookies, chocolate chip, per lb.",5.352,5.255,-1.812407
"Corn, canned, any style, all sizes, per lb.",1.298,1.312,1.078582
"Eggs, grade A, large, per doz.",2.577,2.500,-2.987971
"Flour, white, all purpose, per lb.",0.565,0.549,-2.831858
"Grapefruit, per lb.",1.578,1.564,-0.887199
"Ground beef, 100% beef, per lb.",6.752,6.739,-0.192536
"Ground beef, lean and extra lean, per lb.",8.191,8.338,1.794653
"Ground chuck, 100% beef, per lb.",6.693,6.703,0.149410
"Ham, boneless, excluding canned, per lb.",5.500,5.616,2.109091
"Ice cream, prepackaged, bulk, regular, per 1/2 gal.",6.236,6.264,0.449006
"Lemons, per lb.",1.971,1.955,-0.811771
"Lettuce, romaine, per lb.",3.379,3.560,5.356614
"Milk, fresh, low-fat, reduced fat, skim, per gal.",3.426,3.409,-0.496205
"Milk, fresh, whole, fortified, per gal.",4.100,4.026,-1.804878
"Orange juice, frozen concentrate, 12 oz. can, per 16 oz.",4.871,4.863,-0.164237
"Oranges, Navel, per lb.",1.536,1.508,-1.822917
"Potato chips, per 16 oz.",6.629,6.827,2.986876
"Potatoes, white, per lb.",0.871,0.866,-0.574053
"Rice, white, long grain, uncooked, per lb.",1.059,1.074,1.416431
"Round roast, USDA Choice, boneless, per lb.",8.546,8.587,0.479757
"Spaghetti and macaroni, per lb.",1.325,1.323,-0.150943
"Steak, round, USDA Choice, boneless, per lb.",9.836,10.095,2.633184
"Steak, sirloin, USDA Choice, boneless, per lb.",13.837,14.191,2.558358
"Strawberries, dry pint, per 12 oz.",3.075,2.929,-4.747967
"Sugar, white, all sizes, per lb.",1.022,1.016,-0.587084
"Tomatoes, field grown, per lb.",1.791,1.902,6.197655
"Yogurt, per 8 oz.",1.564,1.498,-4.219949

### Export table

In [25]:
transposed_latest_rows.to_csv('data/bls_table.csv')

## Consumer Price Index

In [26]:
data = {
    "seriesid": ['CUSR0000SA0'],  
    "startyear": "2021",
    "endyear": "2026",
    "registrationkey": api_key
}

response = requests.post(url, data=json.dumps(data), headers=headers)
response_data = response.json()

In [27]:
response_data

{'status': 'REQUEST_SUCCEEDED',
 'responseTime': 98,
 'message': [],
 'Results': {'series': [{'seriesID': 'CUSR0000SA0',
    'data': [{'year': '2026',
      'period': 'M02',
      'periodName': 'February',
      'latest': 'true',
      'value': '327.460',
      'footnotes': [{}]},
     {'year': '2026',
      'period': 'M01',
      'periodName': 'January',
      'value': '326.588',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M12',
      'periodName': 'December',
      'value': '326.031',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M11',
      'periodName': 'November',
      'value': '325.063',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M10',
      'periodName': 'October',
      'value': '-',
      'footnotes': [{'code': 'X',
        'text': 'Data unavailable due to the 2025 lapse in appropriations'}]},
     {'year': '2025',
      'period': 'M09',
      'periodName': 'September',
      'value': '324.245',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M08',
      'periodName': 'August',
      'value': '323.291',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'value': '322.169',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '321.435',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '320.620',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '320.302',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '319.785',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '319.679',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '318.961',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M12',
      'periodName': 'December',
      'value': '317.604',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M11',
      'periodName': 'November',
      'value': '316.528',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M10',
      'periodName': 'October',
      'value': '315.631',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M09',
      'periodName': 'September',
      'value': '314.732',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M08',
      'periodName': 'August',
      'value': '314.062',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M07',
      'periodName': 'July',
      'value': '313.569',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M06',
      'periodName': 'June',
      'value': '313.044',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M05',
      'periodName': 'May',
      'value': '313.175',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M04',
      'periodName': 'April',
      'value': '313.023',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M03',
      'periodName': 'March',
      'value': '312.345',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M02',
      'periodName': 'February',
      'value': '310.967',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M01',
      'periodName': 'January',
      'value': '309.698',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M12',
      'periodName': 'December',
      'value': '308.741',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M11',
      'periodName': 'November',
      'value': '308.148',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M10',
      'periodName': 'October',
      'value': '307.696',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M09',
      'periodName': 'September',
      'value': '307.276',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M08',
      'periodName': 'August',
      'value': '306.082',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M07',
      'periodName': 'July',
      'value': '304.609',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M06',
      'periodName': 'June',
      'value': '304.014',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M05',
      'periodName': 'May',
      'value': '303.334',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M04',
      'periodName': 'April',
      'value': '302.845',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M03',
      'periodName': 'March',
      'value': '301.821',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M02',
      'periodName': 'February',
      'value': '301.450',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M01',
      'periodName': 'January',
      'value': '300.420',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M12',
      'periodName': 'December',
      'value': '298.832',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M11',
      'periodName': 'November',
      'value': '298.786',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M10',
      'periodName': 'October',
      'value': '298.007',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M09',
      'periodName': 'September',
      'value': '296.349',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M08',
      'periodName': 'August',
      'value': '295.097',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M07',
      'periodName': 'July',
      'value': '294.913',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M06',
      'periodName': 'June',
      'value': '294.957',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M05',
      'periodName': 'May',
      'value': '291.298',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M04',
      'periodName': 'April',
      'value': '288.561',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M03',
      'periodName': 'March',
      'value': '287.674',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M02',
      'periodName': 'February',
      'value': '284.500',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M01',
      'periodName': 'January',
      'value': '282.543',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M12',
      'periodName': 'December',
      'value': '280.845',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M11',
      'periodName': 'November',
      'value': '278.919',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M10',
      'periodName': 'October',
      'value': '276.550',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M09',
      'periodName': 'September',
      'value': '273.910',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M08',
      'periodName': 'August',
      'value': '272.676',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M07',
      'periodName': 'July',
      'value': '271.903',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M06',
      'periodName': 'June',
      'value': '270.654',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M05',
      'periodName': 'May',
      'value': '268.383',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M04',
      'periodName': 'April',
      'value': '266.614',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M03',
      'periodName': 'March',
      'value': '264.961',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M02',
      'periodName': 'February',
      'value': '263.579',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M01',
      'periodName': 'January',
      'value': '262.687',
      'footnotes': [{}]}]}]}}

In [28]:
series_data = response_data['Results']['series'][0]['data']

# Convert to DataFrame for easier manipulation
df = pd.DataFrame(series_data)
df['value'] = pd.to_numeric(df['value'], errors='coerce')
df['date'] = pd.to_datetime(df['year'] + '-' + df['period'].str.replace('M', '') + '-01')
df = df.sort_values('date')

# Calculate 12-month percentage change
df['CPI'] = df['value'].pct_change(periods=12, fill_method=None) * 100

print(df[['date', 'value', 'CPI']].tail())

        date    value       CPI
4 2025-10-01      NaN       NaN
3 2025-11-01  325.063  2.696444
2 2025-12-01  326.031  2.653304
1 2026-01-01  326.588  2.391201
0 2026-02-01  327.460  2.434004

In [29]:
df = df[df['year'] != '2020']

In [30]:
df.head()

    year period periodName latest    value footnotes       date  CPI
61  2021    M01    January    NaN  262.687      [{}] 2021-01-01  NaN
60  2021    M02   February    NaN  263.579      [{}] 2021-02-01  NaN
59  2021    M03      March    NaN  264.961      [{}] 2021-03-01  NaN
58  2021    M04      April    NaN  266.614      [{}] 2021-04-01  NaN
57  2021    M05        May    NaN  268.383      [{}] 2021-05-01  NaN

In [31]:
df.to_csv('data/cpi_inflation.csv', index=False)

## Core inflation

In [32]:
data = {
    "seriesid": ['CUSR0000SA0L1E'],  
    "startyear": "2021",
    "endyear": "2026",
    "registrationkey": api_key
}

response = requests.post(url, data=json.dumps(data), headers=headers)
response_data = response.json()

In [33]:
response_data

{'status': 'REQUEST_SUCCEEDED',
 'responseTime': 90,
 'message': [],
 'Results': {'series': [{'seriesID': 'CUSR0000SA0L1E',
    'data': [{'year': '2026',
      'period': 'M02',
      'periodName': 'February',
      'latest': 'true',
      'value': '333.512',
      'footnotes': [{}]},
     {'year': '2026',
      'period': 'M01',
      'periodName': 'January',
      'value': '332.793',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M12',
      'periodName': 'December',
      'value': '331.814',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M11',
      'periodName': 'November',
      'value': '331.043',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M10',
      'periodName': 'October',
      'value': '-',
      'footnotes': [{'code': 'X',
        'text': 'Data unavailable due to the 2025 lapse in appropriations'}]},
     {'year': '2025',
      'period': 'M09',
      'periodName': 'September',
      'value': '330.418',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M08',
      'periodName': 'August',
      'value': '329.700',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'value': '328.682',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '327.658',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '326.893',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '326.467',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '325.690',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '325.465',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '324.638',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M12',
      'periodName': 'December',
      'value': '323.259',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M11',
      'periodName': 'November',
      'value': '322.657',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M10',
      'periodName': 'October',
      'value': '321.731',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M09',
      'periodName': 'September',
      'value': '320.732',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M08',
      'periodName': 'August',
      'value': '319.750',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M07',
      'periodName': 'July',
      'value': '318.940',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M06',
      'periodName': 'June',
      'value': '318.390',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M05',
      'periodName': 'May',
      'value': '318.095',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M04',
      'periodName': 'April',
      'value': '317.649',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M03',
      'periodName': 'March',
      'value': '316.792',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M02',
      'periodName': 'February',
      'value': '315.564',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M01',
      'periodName': 'January',
      'value': '314.319',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M12',
      'periodName': 'December',
      'value': '313.195',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M11',
      'periodName': 'November',
      'value': '312.392',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M10',
      'periodName': 'October',
      'value': '311.457',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M09',
      'periodName': 'September',
      'value': '310.539',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M08',
      'periodName': 'August',
      'value': '309.580',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M07',
      'periodName': 'July',
      'value': '308.960',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M06',
      'periodName': 'June',
      'value': '308.322',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M05',
      'periodName': 'May',
      'value': '307.652',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M04',
      'periodName': 'April',
      'value': '306.534',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M03',
      'periodName': 'March',
      'value': '305.147',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M02',
      'periodName': 'February',
      'value': '304.123',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M01',
      'periodName': 'January',
      'value': '302.642',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M12',
      'periodName': 'December',
      'value': '301.394',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M11',
      'periodName': 'November',
      'value': '300.325',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M10',
      'periodName': 'October',
      'value': '299.399',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M09',
      'periodName': 'September',
      'value': '298.226',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M08',
      'periodName': 'August',
      'value': '296.535',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M07',
      'periodName': 'July',
      'value': '295.088',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M06',
      'periodName': 'June',
      'value': '294.050',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M05',
      'periodName': 'May',
      'value': '292.063',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M04',
      'periodName': 'April',
      'value': '290.514',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M03',
      'periodName': 'March',
      'value': '289.056',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M02',
      'periodName': 'February',
      'value': '288.273',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M01',
      'periodName': 'January',
      'value': '286.757',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M12',
      'periodName': 'December',
      'value': '285.180',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M11',
      'periodName': 'November',
      'value': '283.406',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M10',
      'periodName': 'October',
      'value': '281.668',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M09',
      'periodName': 'September',
      'value': '279.698',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M08',
      'periodName': 'August',
      'value': '278.997',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M07',
      'periodName': 'July',
      'value': '278.648',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M06',
      'periodName': 'June',
      'value': '277.651',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M05',
      'periodName': 'May',
      'value': '275.465',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M04',
      'periodName': 'April',
      'value': '273.660',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M03',
      'periodName': 'March',
      'value': '271.459',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M02',
      'periodName': 'February',
      'value': '270.793',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M01',
      'periodName': 'January',
      'value': '270.387',
      'footnotes': [{}]}]}]}}

In [34]:
series_data = response_data['Results']['series'][0]['data']

# Convert to DataFrame for easier manipulation
df = pd.DataFrame(series_data)
df['value'] = pd.to_numeric(df['value'], errors='coerce')
df['date'] = pd.to_datetime(df['year'] + '-' + df['period'].str.replace('M', '') + '-01')
df = df.sort_values('date')

# Calculate 12-month percentage change
df['Core CPI'] = df['value'].pct_change(periods=12, fill_method=None) * 100

print(df[['date', 'value', 'Core CPI']].tail())

        date    value  Core CPI
4 2025-10-01      NaN       NaN
3 2025-11-01  331.043  2.599045
2 2025-12-01  331.814  2.646485
1 2026-01-01  332.793  2.512029
0 2026-02-01  333.512  2.472462

In [35]:
df = df[df['year'] != '2020']

In [36]:
df.head()

    year period periodName latest    value footnotes       date  Core CPI
61  2021    M01    January    NaN  270.387      [{}] 2021-01-01       NaN
60  2021    M02   February    NaN  270.793      [{}] 2021-02-01       NaN
59  2021    M03      March    NaN  271.459      [{}] 2021-03-01       NaN
58  2021    M04      April    NaN  273.660      [{}] 2021-04-01       NaN
57  2021    M05        May    NaN  275.465      [{}] 2021-05-01       NaN

In [37]:
df.to_csv('data/cpi_core.csv', index=False)

## Food index

In [38]:
data = {
    "seriesid": ['CUSR0000SAF1'],  # Food index, seasonally adjusted
    "startyear": "2021",
    "endyear": "2026",
    "registrationkey": api_key
}

In [39]:
response = requests.post(url, data=json.dumps(data), headers=headers)
response_data = response.json()

In [40]:
response_data

{'status': 'REQUEST_SUCCEEDED',
 'responseTime': 84,
 'message': [],
 'Results': {'series': [{'seriesID': 'CUSR0000SAF1',
    'data': [{'year': '2026',
      'period': 'M02',
      'periodName': 'February',
      'latest': 'true',
      'value': '346.622',
      'footnotes': [{}]},
     {'year': '2026',
      'period': 'M01',
      'periodName': 'January',
      'value': '345.271',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M12',
      'periodName': 'December',
      'value': '344.632',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M11',
      'periodName': 'November',
      'value': '342.386',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M10',
      'periodName': 'October',
      'value': '-',
      'footnotes': [{'code': 'X',
        'text': 'Data unavailable due to the 2025 lapse in appropriations'}]},
     {'year': '2025',
      'period': 'M09',
      'periodName': 'September',
      'value': '342.086',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M08',
      'periodName': 'August',
      'value': '341.320',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'value': '339.891',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '339.468',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '338.474',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '337.493',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '337.331',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '336.065',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '335.441',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M12',
      'periodName': 'December',
      'value': '334.464',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M11',
      'periodName': 'November',
      'value': '333.629',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M10',
      'periodName': 'October',
      'value': '332.463',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M09',
      'periodName': 'September',
      'value': '331.753',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M08',
      'periodName': 'August',
      'value': '330.748',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M07',
      'periodName': 'July',
      'value': '330.329',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M06',
      'periodName': 'June',
      'value': '329.600',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M05',
      'periodName': 'May',
      'value': '328.949',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M04',
      'periodName': 'April',
      'value': '328.449',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M03',
      'periodName': 'March',
      'value': '327.774',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M02',
      'periodName': 'February',
      'value': '327.707',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M01',
      'periodName': 'January',
      'value': '327.424',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M12',
      'periodName': 'December',
      'value': '326.434',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M11',
      'periodName': 'November',
      'value': '325.930',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M10',
      'periodName': 'October',
      'value': '325.442',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M09',
      'periodName': 'September',
      'value': '324.379',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M08',
      'periodName': 'August',
      'value': '324.042',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M07',
      'periodName': 'July',
      'value': '323.201',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M06',
      'periodName': 'June',
      'value': '322.365',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M05',
      'periodName': 'May',
      'value': '322.009',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M04',
      'periodName': 'April',
      'value': '321.213',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M03',
      'periodName': 'March',
      'value': '320.554',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M02',
      'periodName': 'February',
      'value': '320.543',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M01',
      'periodName': 'January',
      'value': '319.300',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M12',
      'periodName': 'December',
      'value': '317.813',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M11',
      'periodName': 'November',
      'value': '316.620',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M10',
      'periodName': 'October',
      'value': '315.038',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M09',
      'periodName': 'September',
      'value': '312.901',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M08',
      'periodName': 'August',
      'value': '310.794',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M07',
      'periodName': 'July',
      'value': '308.193',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M06',
      'periodName': 'June',
      'value': '304.834',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M05',
      'periodName': 'May',
      'value': '301.755',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M04',
      'periodName': 'April',
      'value': '298.339',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M03',
      'periodName': 'March',
      'value': '295.546',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M02',
      'periodName': 'February',
      'value': '292.899',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M01',
      'periodName': 'January',
      'value': '290.077',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M12',
      'periodName': 'December',
      'value': '287.812',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M11',
      'periodName': 'November',
      'value': '286.151',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M10',
      'periodName': 'October',
      'value': '283.972',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M09',
      'periodName': 'September',
      'value': '281.366',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M08',
      'periodName': 'August',
      'value': '279.010',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M07',
      'periodName': 'July',
      'value': '277.813',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M06',
      'periodName': 'June',
      'value': '275.997',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M05',
      'periodName': 'May',
      'value': '273.932',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M04',
      'periodName': 'April',
      'value': '272.715',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M03',
      'periodName': 'March',
      'value': '271.636',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M02',
      'periodName': 'February',
      'value': '271.425',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M01',
      'periodName': 'January',
      'value': '271.195',
      'footnotes': [{}]}]}]}}

In [41]:
series_data = response_data['Results']['series'][0]['data']

# Convert to DataFrame for easier manipulation
df = pd.DataFrame(series_data)
df['value'] = pd.to_numeric(df['value'], errors='coerce')
df['date'] = pd.to_datetime(df['year'] + '-' + df['period'].str.replace('M', '') + '-01')
df = df.sort_values('date')

# Calculate 12-month percentage change
df['Food index'] = df['value'].pct_change(periods=12, fill_method=None) * 100

print(df[['date', 'value', 'Food index']].tail())

        date    value  Food index
4 2025-10-01      NaN         NaN
3 2025-11-01  342.386    2.624772
2 2025-12-01  344.632    3.040088
1 2026-01-01  345.271    2.930471
0 2026-02-01  346.622    3.141357

In [42]:
df = df[df['year'] != '2020']

In [43]:
df.to_csv('data/cpi_food.csv', index=False)

## Combine Data

In [44]:
cpi = pd.read_csv('data/cpi_inflation.csv')
cpi_core = pd.read_csv('data/cpi_core.csv')
food_index = pd.read_csv('data/cpi_food.csv')

In [45]:
merged_cpi = cpi.merge(cpi_core, on='date', how='inner', suffixes=('_cpi', '_core'))
merged_cpi.head()

,year_cpi,period_cpi,periodName_cpi,latest_cpi,value_cpi,footnotes_cpi,date,CPI,year_core,period_core,periodName_core,latest_core,value_core,footnotes_core,Core CPI
0,2021,M01,January,NaN,262.687,[{}],2021-01-01,NaN,2021,M01,January,NaN,270.387,[{}],NaN
1,2021,M02,February,NaN,263.579,[{}],2021-02-01,NaN,2021,M02,February,NaN,270.793,[{}],NaN
2,2021,M03,March,NaN,264.961,[{}],2021-03-01,NaN,2021,M03,March,NaN,271.459,[{}],NaN
3,2021,M04,April,NaN,266.614,[{}],2021-04-01,NaN,2021,M04,April,NaN,273.660,[{}],NaN
4,2021,M05,May,NaN,268.383,[{}],2021-05-01,NaN,2021,M05,May,NaN,275.465,[{}],NaN

In [46]:
merged_cpi.to_csv('data/cpi_merged.csv', index=False)

In [47]:
food_index = pd.read_csv('data/cpi_food.csv')
cpi = pd.read_csv('data/cpi_inflation.csv')

merged_food_cpi = food_index.merge(cpi, on='date', how='inner', suffixes=('_food', '_cpi'))
merged_food_cpi.head()

,year_food,period_food,periodName_food,latest_food,value_food,footnotes_food,date,Food index,year_cpi,period_cpi,periodName_cpi,latest_cpi,value_cpi,footnotes_cpi,CPI
0,2021,M01,January,NaN,271.195,[{}],2021-01-01,NaN,2021,M01,January,NaN,262.687,[{}],NaN
1,2021,M02,February,NaN,271.425,[{}],2021-02-01,NaN,2021,M02,February,NaN,263.579,[{}],NaN
2,2021,M03,March,NaN,271.636,[{}],2021-03-01,NaN,2021,M03,March,NaN,264.961,[{}],NaN
3,2021,M04,April,NaN,272.715,[{}],2021-04-01,NaN,2021,M04,April,NaN,266.614,[{}],NaN
4,2021,M05,May,NaN,273.932,[{}],2021-05-01,NaN,2021,M05,May,NaN,268.383,[{}],NaN

In [48]:
merged_food_cpi.to_csv('data/cpi_food_merged.csv', index=False)

In [50]:
data = {
    "seriesid": ['CUSR0000SA0'],  
    "startyear": "2021",
    "endyear": "2026",
    "registrationkey": api_key
}

In [51]:
response = requests.post(url, data=json.dumps(data), headers=headers)
response_data = response.json()

In [52]:
response_data

{'status': 'REQUEST_SUCCEEDED',
 'responseTime': 290,
 'message': ['Database is locked for Series CUSR0000SA0'],
 'Results': {'series': [{'seriesID': 'CUSR0000SA0', 'data': []}]}}